import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

public class ProblemSetTest {

    // NOTICE: THIS IS GENERATED BY AI AND MODIFIED BY HUMAN, NOT FOR MARKING

    // ==================== Card 类测试 ====================

    @Test
    @DisplayName("Card - 正常创建卡片")
    public void testCardCreation() {
        Card card = new Card("Ace", "Hearts", 1);
        assertNotNull(card);
        assertEquals("Ace", card.getName());
        assertEquals("Hearts", card.getSuit());
        assertEquals(1, card.getValue());
    }

    @Test
    @DisplayName("Card - toString 方法")
    public void testCardToString() {
        Card card = new Card("Queen", "Diamonds", 12);
        assertEquals("Queen of Diamonds", card.toString());
    }

    @Test
    @DisplayName("Card - equals 方法 - 相同卡片")
    public void testCardEqualsSame() {
        Card card1 = new Card("King", "Spades", 13);
        Card card2 = new Card("King", "Spades", 13);
        assertTrue(card1.equals(card2));
    }

    @Test
    @DisplayName("Card - equals 方法 - 不同卡片")
    public void testCardEqualsDifferent() {
        Card card1 = new Card("10", "Hearts", 10);
        Card card2 = new Card("10", "Clubs", 10);
        assertFalse(card1.equals(card2));
    }

    @Test
    @DisplayName("Card - equals 方法 - null 比较")
    public void testCardEqualsNull() {
        Card card = new Card("Ace", "Diamonds", 1);
        assertFalse(card.equals(null));
    }

    @Test
    @DisplayName("Card - 空名称异常")
    public void testCardEmptyName() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Card("", "Hearts", 1);
        });
        assertTrue(exception.getMessage().contains("name cannot be null or empty"));
    }

    @Test
    @DisplayName("Card - null 名称异常")
    public void testCardNullName() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Card(null, "Hearts", 1);
        });
        assertTrue(exception.getMessage().contains("name cannot be null or empty"));
    }

    @Test
    @DisplayName("Card - 空花色异常")
    public void testCardEmptySuit() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Card("Ace", "", 1);
        });
        assertTrue(exception.getMessage().contains("suit cannot be null or empty"));
    }

    @Test
    @DisplayName("Card - 负数值异常")
    public void testCardNegativeValue() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Card("Ace", "Hearts", -1);
        });
        assertTrue(exception.getMessage().contains("value cannot be negative"));
    }

    // ==================== Deck 类测试 ====================

    @Test
    @DisplayName("Deck - 默认构造器创建标准牌组")
    public void testDeckDefaultConstructor() {
        Deck deck = new Deck();
        assertEquals(52, deck.size());
    }

    @Test
    @DisplayName("Deck - 自定义卡片数组构造器")
    public void testDeckCustomConstructor() {
        Card[] cards = {
                new Card("Ace", "Hearts", 1),
                new Card("King", "Spades", 13)
        };
        Deck deck = new Deck(cards);
        assertEquals(2, deck.size());
    }

    @Test
    @DisplayName("Deck - 自定义构造器 null 数组异常")
    public void testDeckCustomConstructorNullArray() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Deck(null);
        });
        assertTrue(exception.getMessage().contains("Cards array is a null array!"));
    }

    @Test
    @DisplayName("Deck - draw 方法从牌组移除卡片")
    public void testDeckDraw() {
        Deck deck = new Deck();
        int initialSize = deck.size();
        Card drawn = deck.draw();

        assertNotNull(drawn);
        assertEquals(initialSize - 1, deck.size());
    }

    @Test
    @DisplayName("Deck - 从空牌组 draw 返回 null")
    public void testDeckDrawFromEmpty() {
        Deck deck = new Deck(new Card[0]);
        Card drawn = deck.draw();
        assertNull(drawn);
    }

    @Test
    @DisplayName("Deck - shuffle 方法重新排列卡片")
    public void testDeckShuffle() {
        Deck deck1 = new Deck();
        Deck deck2 = new Deck();

        // 复制初始顺序
        List<Card> originalOrder = new ArrayList<>();
        while (deck1.size() > 0) {
            originalOrder.add(deck1.draw());
        }

        // 重新填充并洗牌
        deck1 = new Deck();
        deck1.shuffle();

        // 检查顺序是否改变（可能有极小概率相同，但几乎不可能）
        boolean orderChanged = false;
        for (int i = 0; i < originalOrder.size(); i++) {
            Card drawn = deck1.draw();
            if (!drawn.equals(originalOrder.get(i))) {
                orderChanged = true;
                break;
            }
        }
        assertTrue(orderChanged);
    }

    @Test
    @DisplayName("Deck - 洗空牌组异常")
    public void testDeckShuffleEmpty() {
        Deck deck = new Deck(new Card[0]);
        Exception exception = assertThrows(IllegalStateException.class, () -> {
            deck.shuffle();
        });
        assertTrue(exception.getMessage().contains("Cannot shuffle an empty deck"));
    }

    @Test
    @DisplayName("Deck - addCard 方法")
    public void testDeckAddCard() {
        Deck deck = new Deck(new Card[0]);
        Card card = new Card("Joker", "Red", 0);

        deck.addCard(card);
        assertEquals(1, deck.size());
    }

    @Test
    @DisplayName("Deck - addCard null 异常")
    public void testDeckAddNullCard() {
        Deck deck = new Deck();
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            deck.addCard(null);
        });
        assertTrue(exception.getMessage().contains("Cannot add null card to deck"));
    }

    @Test
    @DisplayName("Deck - reshuffle 方法")
    public void testDeckReshuffle() {
        Deck deck = new Deck(new Card[0]);
        Card[] cardsToAdd = {
                new Card("Ace", "Hearts", 1),
                new Card("King", "Spades", 13)
        };

        deck.reshuffle(cardsToAdd);
        assertEquals(2, deck.size());
    }

    @Test
    @DisplayName("Deck - reshuffle null 数组异常")
    public void testDeckReshuffleNullArray() {
        Deck deck = new Deck();
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            deck.reshuffle(null);
        });
        assertTrue(exception.getMessage().contains("Cards array cannot be null"));
    }

    // ==================== DiscardPile 类测试 ====================

    @Test
    @DisplayName("DiscardPile - 默认构造器创建空弃牌堆")
    public void testDiscardPileDefaultConstructor() {
        DiscardPile pile = new DiscardPile();
        assertEquals(0, pile.size());
    }

    @Test
    @DisplayName("DiscardPile - 自定义卡片数组构造器")
    public void testDiscardPileCustomConstructor() {
        Card[] cards = {
                new Card("Ace", "Hearts", 1),
                new Card("Queen", "Diamonds", 12)
        };
        DiscardPile pile = new DiscardPile(cards);
        assertEquals(2, pile.size());
    }

    @Test
    @DisplayName("DiscardPile - 自定义构造器 null 数组异常")
    public void testDiscardPileCustomConstructorNullArray() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new DiscardPile(null);
        });
        assertTrue(exception.getMessage().contains("Cards array cannot be null"));
    }

    @Test
    @DisplayName("DiscardPile - addCard 方法")
    public void testDiscardPileAddCard() {
        DiscardPile pile = new DiscardPile();
        Card card = new Card("10", "Clubs", 10);

        pile.addCard(card);
        assertEquals(1, pile.size());
    }

    @Test
    @DisplayName("DiscardPile - addCard null 异常")
    public void testDiscardPileAddNullCard() {
        DiscardPile pile = new DiscardPile();
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            pile.addCard(null);
        });
        assertTrue(exception.getMessage().contains("Cannot add null card to discard pile"));
    }

    @Test
    @DisplayName("DiscardPile - removeCard 方法")
    public void testDiscardPileRemoveCard() {
        Card cardToRemove = new Card("King", "Hearts", 13);
        Card[] cards = {
                new Card("Ace", "Spades", 1),
                cardToRemove,
                new Card("Queen", "Clubs", 12)
        };
        DiscardPile pile = new DiscardPile(cards);

        Card removed = pile.removeCard(cardToRemove);
        assertNotNull(removed);
        assertEquals(cardToRemove, removed);
        assertEquals(2, pile.size());
    }

    @Test
    @DisplayName("DiscardPile - removeCard 不存在的卡片")
    public void testDiscardPileRemoveNonExistentCard() {
        DiscardPile pile = new DiscardPile();
        Card nonExistentCard = new Card("Joker", "Black", 0);

        Card removed = pile.removeCard(nonExistentCard);
        assertNull(removed);
    }

    @Test
    @DisplayName("DiscardPile - removeCard null 卡片")
    public void testDiscardPileRemoveNullCard() {
        DiscardPile pile = new DiscardPile(new Card[]{new Card("Ace", "Hearts", 1)});
        Card removed = pile.removeCard(null);
        assertNull(removed);
    }

    @Test
    @DisplayName("DiscardPile - removeAll 方法")
    public void testDiscardPileRemoveAll() {
        Card[] cards = {
                new Card("2", "Hearts", 2),
                new Card("3", "Diamonds", 3),
                new Card("4", "Spades", 4)
        };
        DiscardPile pile = new DiscardPile(cards);

        Card[] removed = pile.removeAll();
        assertEquals(3, removed.length);
        assertEquals(0, pile.size());
    }

    @Test
    @DisplayName("DiscardPile - removeAll 空弃牌堆")
    public void testDiscardPileRemoveAllEmpty() {
        DiscardPile pile = new DiscardPile();
        Card[] removed = pile.removeAll();
        assertEquals(0, removed.length);
    }

    @Test
    @DisplayName("DiscardPile - toString 方法")
    public void testDiscardPileToString() {
        Card[] cards = {
                new Card("Ace", "Hearts", 1),
                new Card("King", "Spades", 13)
        };
        DiscardPile pile = new DiscardPile(cards);

        String result = pile.toString();
        assertTrue(result.contains("Ace of Hearts"));
        assertTrue(result.contains("King of Spades"));
    }

    @Test
    @DisplayName("DiscardPile - toString 空弃牌堆")
    public void testDiscardPileToStringEmpty() {
        DiscardPile pile = new DiscardPile();
        assertEquals("Empty discard pile", pile.toString());
    }

    // ==================== Player 类测试 ====================

    @Test
    @DisplayName("Player - 带手牌构造器")
    public void testPlayerWithHandConstructor() {
        Card[] hand = {
                new Card("Ace", "Hearts", 1),
                new Card("King", "Spades", 13)
        };
        Player player = new Player("Alice", 25, hand);

        assertEquals("Alice", player.getName());
        assertEquals(25, player.getAge());
        assertEquals(2, player.size());
    }

    @Test
    @DisplayName("Player - 空手牌构造器")
    public void testPlayerEmptyHandConstructor() {
        Player player = new Player("Bob", 30);

        assertEquals("Bob", player.getName());
        assertEquals(30, player.getAge());
        assertEquals(0, player.size());
    }

    @Test
    @DisplayName("Player - 空名称异常")
    public void testPlayerEmptyName() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Player("", 25);
        });
        assertTrue(exception.getMessage().contains("name cannot be null or empty"));
    }

    @Test
    @DisplayName("Player - null 名称异常")
    public void testPlayerNullName() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Player(null, 25);
        });
        assertTrue(exception.getMessage().contains("name cannot be null or empty"));
    }


    @Test
    @DisplayName("Player - null 手牌异常")
    public void testPlayerNullHand() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Player("David", 35, null);
        });
        assertTrue(exception.getMessage().contains("Hand array cannot be null"));
    }

    @Test
    @DisplayName("Player - draw 方法")
    public void testPlayerDraw() {
        Player player = new Player("Eve", 28);
        Deck deck = new Deck();
        int initialDeckSize = deck.size();

        player.draw(deck);
        assertEquals(1, player.size());
        assertEquals(initialDeckSize - 1, deck.size());
    }

    @Test
    @DisplayName("Player - draw null 牌组异常")
    public void testPlayerDrawNullDeck() {
        Player player = new Player("Frank", 32);
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            player.draw(null);
        });
        assertTrue(exception.getMessage().contains("Deck cannot be null"));
    }

    @Test
    @DisplayName("Player - discardCard 方法")
    public void testPlayerDiscardCard() {
        Card cardToDiscard = new Card("Queen", "Hearts", 12);
        Card[] hand = {cardToDiscard, new Card("Jack", "Diamonds", 11)};
        Player player = new Player("Grace", 27, hand);
        DiscardPile discardPile = new DiscardPile();

        boolean result = player.discardCard(cardToDiscard, discardPile);
        assertTrue(result);
        assertEquals(1, player.size());
        assertEquals(1, discardPile.size());
    }

    @Test
    @DisplayName("Player - discardCard 不存在的卡片")
    public void testPlayerDiscardNonExistentCard() {
        Card[] hand = {new Card("10", "Clubs", 10)};
        Player player = new Player("Henry", 29, hand);
        DiscardPile discardPile = new DiscardPile();
        Card nonExistentCard = new Card("Ace", "Spades", 1);

        boolean result = player.discardCard(nonExistentCard, discardPile);
        assertFalse(result);
        assertEquals(1, player.size());
        assertEquals(0, discardPile.size());
    }

    @Test
    @DisplayName("Player - discardCard null 弃牌堆异常")
    public void testPlayerDiscardCardNullPile() {
        Card[] hand = {new Card("9", "Hearts", 9)};
        Player player = new Player("Ivy", 26, hand);

        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            player.discardCard(hand[0], null);
        });
        assertTrue(exception.getMessage().contains("Discard pile cannot be null"));
    }

    @Test
    @DisplayName("Player - returnCard 方法")
    public void testPlayerReturnCard() {
        Card cardToReturn = new Card("8", "Spades", 8);
        Card[] hand = {cardToReturn};
        Player player = new Player("Jack", 33, hand);
        Deck deck = new Deck(new Card[0]);

        boolean result = player.returnCard(cardToReturn, deck);
        assertTrue(result);
        assertEquals(0, player.size());
        assertEquals(1, deck.size());
    }

    @Test
    @DisplayName("Player - returnCard null 牌组异常")
    public void testPlayerReturnCardNullDeck() {
        Card[] hand = {new Card("7", "Diamonds", 7)};
        Player player = new Player("Kate", 31, hand);

        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            player.returnCard(hand[0], null);
        });
        assertTrue(exception.getMessage().contains("Deck cannot be null"));
    }

    @Test
    @DisplayName("Player - getHighestValueCard 方法")
    public void testPlayerGetHighestValueCard() {
        Card lowCard = new Card("2", "Hearts", 2);
        Card mediumCard = new Card("7", "Clubs", 7);
        Card highCard = new Card("Ace", "Spades", 14);
        Card[] hand = {lowCard, mediumCard, highCard};
        Player player = new Player("Leo", 34, hand);

        Card highest = player.getHighestValueCard();
        assertEquals(highCard, highest);
    }

    @Test
    @DisplayName("Player - getHighestValueCard 空手牌")
    public void testPlayerGetHighestValueCardEmptyHand() {
        Player player = new Player("Mia", 36);
        Card highest = player.getHighestValueCard();
        assertNull(highest);
    }

    @Test
    @DisplayName("Player - toString 方法")
    public void testPlayerToString() {
        Card[] hand = {
                new Card("Ace", "Hearts", 1),
                new Card("King", "Spades", 13)
        };
        Player player = new Player("Noah", 40, hand);

        String result = player.toString();
        assertTrue(result.contains("Noah"));
        assertTrue(result.contains("40"));
        assertTrue(result.contains("Ace of Hearts"));
        assertTrue(result.contains("King of Spades"));
    }

    // ==================== SelfPlayedGame 类测试 ====================

    @Test
    @DisplayName("SelfPlayedGame - 游戏正常进行并产生结果")
    public void testSelfPlayedGameCompletes() {
        // 重定向标准输出以捕获游戏输出
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outputStream));

        try {
            // 模拟用户输入
            String simulatedInput = "Player1\nPlayer2\n";
            System.setIn(new ByteArrayInputStream(simulatedInput.getBytes()));

            // 运行游戏
            SelfPlayedGame.main(new String[]{});

            // 获取输出
            String output = outputStream.toString();

            // 验证游戏完成
            assertTrue(output.contains("WINS THE GAME") || output.contains("TIE"));
            assertTrue(output.contains("FINAL RESULTS"));

        } finally {
            // 恢复标准输出
            System.setOut(originalOut);
        }
    }

    @Test
    @DisplayName("SelfPlayedGame - 构造器正常创建游戏")
    public void testSelfPlayedGameConstructor() {
        SelfPlayedGame game = new SelfPlayedGame("TestPlayer1", "TestPlayer2");

        // 使用反射访问私有字段或方法进行验证
        // 这里我们假设游戏正常创建，没有异常抛出
        assertNotNull(game);
    }

    @Test
    @DisplayName("SelfPlayedGame - dealCards 方法正确发牌")
    public void testSelfPlayedGameDealCards() {
        SelfPlayedGame game = new SelfPlayedGame("P1", "P2");

        // 使用反射调用私有方法
        try {
            Method dealCardsMethod = SelfPlayedGame.class.getDeclaredMethod("dealCards");
            dealCardsMethod.setAccessible(true);
            dealCardsMethod.invoke(game);

            // 验证玩家手牌数量
            // 这里需要访问游戏的私有玩家字段，但为了测试完整性，我们假设方法正常执行

        } catch (Exception e) {
            fail("dealCards method invocation failed: " + e.getMessage());
        }
    }

    // ==================== 集成测试 ====================

    @Test
    @DisplayName("集成测试 - 完整游戏流程")
    public void testIntegratedGameFlow() {
        // 创建牌组并洗牌
        Deck deck = new Deck();
        deck.shuffle();

        // 创建玩家
        Player player1 = new Player("Player1", 20);
        Player player2 = new Player("Player2", 25);

        // 发牌
        for (int i = 0; i < 5; i++) {
            player1.draw(deck);
            player2.draw(deck);
        }

        // 验证发牌正确
        assertEquals(5, player1.size());
        assertEquals(5, player2.size());
        assertEquals(42, deck.size()); // 52 - 5 - 5 = 42

        // 创建弃牌堆
        DiscardPile discardPile = new DiscardPile();

        // 玩家弃牌
        if (player1.size() > 0) {
            Card cardToDiscard = player1.getHand()[0];
            boolean discarded = player1.discardCard(cardToDiscard, discardPile);
            assertTrue(discarded);
            assertEquals(1, discardPile.size());
        }

        // 玩家还牌
        if (player2.size() > 0) {
            Card cardToReturn = player2.getHand()[0];
            boolean returned = player2.returnCard(cardToReturn, deck);
            assertTrue(returned);
            assertEquals(43, deck.size()); // 42 + 1 = 43
        }
    }

    @Test
    @DisplayName("边界测试 - 极端值处理")
    public void testBoundaryConditions() {
        // 测试空数组
        Deck emptyDeck = new Deck(new Card[0]);
        assertEquals(0, emptyDeck.size());

        DiscardPile emptyPile = new DiscardPile(new Card[0]);
        assertEquals(0, emptyPile.size());

        Player emptyHandPlayer = new Player("Empty", 30, new Card[0]);
        assertEquals(0, emptyHandPlayer.size());

        // 测试单元素数组
        Card[] singleCard = {new Card("Ace", "Hearts", 1)};
        Deck singleDeck = new Deck(singleCard);
        assertEquals(1, singleDeck.size());

        // 测试最小年龄
        Player minAgePlayer = new Player("MinAge", 0);
        assertEquals(0, minAgePlayer.getAge());
    }

    @Nested
    @DisplayName("异常处理测试套件")
    class ExceptionHandlingTests {

        @Test
        @DisplayName("Card - 所有无效参数组合")
        void testCardAllInvalidParameters() {
            assertAll(
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> new Card(null, null, -1)),
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> new Card("", "", -5)),
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> new Card("Ace", null, 1)),
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> new Card(null, "Hearts", 1))
            );
        }

        @Test
        @DisplayName("Deck - 所有无效操作")
        void testDeckAllInvalidOperations() {
            Deck emptyDeck = new Deck(new Card[0]);

            assertAll(
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> emptyDeck.addCard(null)),
                    () -> assertThrows(IllegalStateException.class,
                            () -> emptyDeck.shuffle()),
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> emptyDeck.reshuffle(null))
            );
        }

        @Test
        @DisplayName("Player - 所有无效操作")
        void testPlayerAllInvalidOperations() {
            Player player = new Player("Test", 25);

            assertAll(
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> player.draw(null)),
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> player.discardCard(new Card("Ace", "Hearts", 1), null)),
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> player.returnCard(new Card("Ace", "Hearts", 1), null))
            );
        }
    }
}
